name: How much revenue are we making each month?
description: Monthly revenue trend showing total basket revenue over time
tableName: dbt_orders
updatedAt: "2026-01-29T18:45:00.000Z"
metricQuery:
  exploreName: dbt_orders
  dimensions:
    - dbt_orders_order_date_month
  metrics:
    - dbt_orders_sum_of_basket_total
  filters: {}
  sorts:
    - fieldId: dbt_orders_order_date_month
      descending: false
  limit: 500
  metricOverrides:
    dbt_orders_sum_of_basket_total:
      formatOptions:
        type: currency
        round: 0
        compact: thousands
        currency: USD
        separator: default
  tableCalculations: []
  additionalMetrics: []
  customDimensions: []
chartConfig:
  type: cartesian
  config:
    layout:
      xField: dbt_orders_order_date_month
      yField:
        - dbt_orders_sum_of_basket_total
    eChartsConfig:
      grid:
        containLabel: true
      xAxis:
        - name: Month
          type: category
      yAxis:
        - name: Revenue
          type: value
      legend:
        show: false
      series:
        - type: bar
          label:
            show: false
          encode:
            xRef:
              field: dbt_orders_order_date_month
            yRef:
              field: dbt_orders_sum_of_basket_total
          yAxisIndex: 0
slug: how-much-revenue-are-we-making-each-week-
tableConfig:
  columnOrder:
    - dbt_orders_order_date_month
    - dbt_orders_sum_of_basket_total
spaceSlug: "-sales"
version: 1
