spotlight:
  default_visibility: show
  categories:
    PoP:
      label: 'Period over Period Metrics'
      color: 'blue'
parameters:
  # Parameter with simple options list
  comparison_period:
    label: "Select Period to Compare"
    type: string
    description: "Compare the selected period with the exact previous period"
    options:
      - "Past 1 week"
      - "Past 1 month"
      - "Past 3 months"
      - "Past 6 months"
      - "Past 1 year"
    default: "Past 1 week"
  partner_select: 
    label: select a partner
    type: string
    description: filter partners
    options_from_dimension: 
      model: dbt_orders
      dimension: partner_name
    default: "All"